install: true
script: zip development-protocol.netcanvas * -r
before_deploy:
  # Set up git user name and tag this commit
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: GH_TOKEN
  file: "development-protocol.netcanvas"
  skip_cleanup: true
  overwrite: true